name: Just for test that send test.txt to private EC2 instance through bastion host 

on:
  push:
    branches: [ "main" ]

jobs:
  just-send:
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub Actions IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Create .env.production for CD Deploy
        run: |
          echo "${{ secrets.CD_DEPLOY_CONFIG }}" > .env.production

      - name: Build
        run: |
          npm run build
          ls

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.BASTION_HOST_PEM_KEY }}

      - name: Authorize GitHub Actions IP in Bastion Host Security Group
        run: |
          aws ec2 authorize-security-group-ingress \
          --group-id ${{ secrets.BASTION_SECURITY_GROUP_ID }} \
          --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
          
      - name: SCP Action
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.BASTION_HOST_IP }}
          username: ec2-user
          key: ${{ secrets.BASTION_HOST_PEM_KEY }}
          source: "./dist/**"
          target: "/home/ec2-user/deploy"
        
      - name: Make Finish Trigger File
        run: |
          echo "1" > send.txt
        
      - name: Send Finish Trigger
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.BASTION_HOST_IP }}
          username: ec2-user
          key: ${{ secrets.BASTION_HOST_PEM_KEY }}
          source: "./send.txt"
          target: "/home/ec2-user/finish"
        
      - name: Revoke GitHub Actions IP in Bastion Host Security Group
        if: ${{ always() }}
        run: |
          aws ec2 revoke-security-group-ingress \
          --group-id ${{ secrets.BASTION_SECURITY_GROUP_ID }} \
          --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Clean up
        run: |
          rm send.txt

      - name: SSH Agent Cleanup
        if: ${{ always() }}
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.BASTION_HOST_PEM_KEY }}
